#!/bin/bash
# =============================================================================
# Server Hardening Script for Ubuntu
# Combines: package updates, UFW firewall, unattended upgrades,
#           non-root user setup, SSH hardening, and optional fail2ban.
#
# Usage: sudo bash server-hardening.sh
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# CONFIGURATION — edit these before running
# -----------------------------------------------------------------------------
read -rp "Enter the non-root username to create: " NEW_USER
if [[ -z "${NEW_USER:-}" ]]; then
    read -rp "Enter the non-root username to create: " NEW_USER
fi
if [[ -z "${NEW_USER}" ]]; then
    echo "ERROR: Username cannot be empty." >&2
    exit 1
fi
SSH_PORT="22"                      # SSH port to expose
ADDRESS_FAMILY="any"               # inet | inet6 | any
PERMIT_ROOT_LOGIN="no"             # yes | no | prohibit-password
PASSWORD_AUTH="no"                 # yes | no  (no = key-only auth)
INSTALL_FAIL2BAN="yes"             # yes | no
# -----------------------------------------------------------------------------

CFG=/etc/ssh/sshd_config

echo "==> [1/5] Updating packages..."
apt update
apt upgrade -y
apt autoremove -y
apt install -y update-notifier-common landscape-common
apt update

echo "==> [2/5] Configuring UFW firewall..."
ufw default deny incoming
ufw default allow outgoing
#ufw allow proto tcp from any to any port 80,443
ufw allow "${SSH_PORT}/tcp"
ufw --force enable

echo "==> [3/5] Enabling unattended security upgrades..."
apt install -y unattended-upgrades

cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
// Generated by server-hardening.sh — see man unattended-upgrades for all options.
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESM:${distro_codename}";
};
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "3";
APT::Periodic::Unattended-Upgrade "1";
EOF

echo "==> [4/5] Creating non-root user: ${NEW_USER}..."
if id "${NEW_USER}" &>/dev/null; then
    echo "    User '${NEW_USER}' already exists, skipping creation."
else
    useradd -m -s "$(getent passwd root | cut -d: -f7)" "${NEW_USER}"
    usermod -p '*' "${NEW_USER}"   # lock password — key-only login
fi

# Add to sudo / wheel group (whichever exists)
if grep -q '^sudo:' /etc/group; then
    usermod -aG sudo "${NEW_USER}"
fi
if grep -q '^wheel:' /etc/group; then
    usermod -aG wheel "${NEW_USER}"
fi

# Passwordless sudo
cat > "/etc/sudoers.d/50-${NEW_USER}-init" <<EOF
# Managed by server-hardening.sh
${NEW_USER} ALL=(ALL) NOPASSWD:ALL
EOF
chmod 440 "/etc/sudoers.d/50-${NEW_USER}-init"

# Copy root's authorised SSH keys to the new user
if [ -f /root/.ssh/authorized_keys ]; then
    mkdir -p "/home/${NEW_USER}/.ssh"
    cp /root/.ssh/authorized_keys "/home/${NEW_USER}/.ssh/authorized_keys"
    chown -R "${NEW_USER}:${NEW_USER}" "/home/${NEW_USER}/.ssh"
    chmod 700 "/home/${NEW_USER}/.ssh"
    chmod 600 "/home/${NEW_USER}/.ssh/authorized_keys"
    echo "    SSH authorised keys copied from root."
else
    echo "    WARNING: /root/.ssh/authorized_keys not found — add keys manually."
fi

echo "==> [5/5] Hardening SSH configuration..."
# Back up the original config once
if [ ! -f "${CFG}.orig" ]; then
    cp "${CFG}" "${CFG}.orig"
fi

# Comment out any existing conflicting directives
sed -i 's|^\(PermitRootLogin .*\)|#\1|g'          "${CFG}"
sed -i 's|^\(PasswordAuthentication .*\)|#\1|g'   "${CFG}"
sed -i 's|^\(Port .*\)|#\1|g'                     "${CFG}"
sed -i 's|^\(AddressFamily .*\)|#\1|g'            "${CFG}"

# Append the desired settings
{
    echo ""
    echo "# --- Added by server-hardening.sh ---"
    echo "PermitRootLogin ${PERMIT_ROOT_LOGIN}"
    echo "PasswordAuthentication ${PASSWORD_AUTH}"
    echo "Port ${SSH_PORT}"
    echo "AddressFamily ${ADDRESS_FAMILY}"
} >> "${CFG}"

# Validate config before restarting
if sshd -t; then
    systemctl restart ssh
    echo "    SSH restarted successfully."
else
    echo "    ERROR: sshd config test failed — restoring backup and aborting."
    cp "${CFG}.orig" "${CFG}"
    exit 1
fi

if [[ "${INSTALL_FAIL2BAN}" == "yes" ]]; then
    echo "==> Installing fail2ban..."
    apt update && apt install -y fail2ban
    systemctl enable --now fail2ban
fi

# -----------------------------------------------------------------------------
echo ""
echo "======================================================"
echo " Server hardening complete."
echo "======================================================"
echo ""
echo " Next steps (manual):"
echo "  * Test login as '${NEW_USER}' before closing this session"
echo "  * Add pm2 save/resurrect commands if running Node apps"
echo "  * Audit who else has root/sudo access"
echo "  * Confirm PASSWORD_AUTH=no only after verifying key login works"
echo "======================================================"
